DROP TABLE IF EXISTS entry;
DROP TABLE IF EXISTS item;
CREATE TABLE entry (
	id INTEGER PRIMARY KEY,
	region TEXT NOT NULL,
	cityFlag INTEGER NOT NULL,
	done INTEGER NOT NULL
);
CREATE TABLE item (
	id INTEGER PRIMARY KEY,
	rent REAL NOT NULL,
	cpi REAL NOT NULL,
	itemName TEXT NOT NULL,
	category TEXT NOT NULL
);